name: Daily Commit

on:
  schedule:
    - cron: '15 12 * * *' # Runs every day at 3:15 PM UTC

jobs:
  commit:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Make Commit
        run: |
          echo "Another day another commit" >> commit.txt
          git add commit.txt
          git commit -m "Automated daily commit"
          git push
