name: Manual Commit

on:
  workflow_dispatch:

jobs:
  ac_daily_commit:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
      - name: powershell allow
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_AC_100_COMMITS }}
          pull: true

      - name: Set Up Git
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Make Commit
        run: |
          echo "Another day another commit" >> commit.txt
          git add commit.txt
          git commit -m "Automated daily commit"
          git push
